"""add fields name and email to userprofile

Revision ID: 2f57019457f3
Revises: 5267e55caf37
Create Date: 2025-06-20 22:03:24.550702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f57019457f3'
down_revision: Union[str, None] = '5267e55caf37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('email', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'name')
    op.drop_column('user_profiles', 'email')
    # ### end Alembic commands ###
