"""ref-user-profile

Revision ID: f941fc77e7d6
Revises: 2f57019457f3
Create Date: 2025-06-21 08:54:28.051612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f941fc77e7d6'
down_revision: Union[str, None] = '2f57019457f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_profiles', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_profiles', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
